steps:
  # Build Frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/jobs-app-400516/jobs-portal/frontend', './apps/frontend', '--build-arg', 'VITE_GOOGLE_LOCATION_API_KEY=$$GOOGLE_LOCATION_API_KEY', '--build-arg', 'VITE_TINYMCE_EDITOR_API_KEY=$$TINYMCE_EDITOR_API_KEY', '--build-arg', 'VITE_BACKEND_URL=https://jobs-portal-backend-1080803823360.europe-west1.run.app']
    secretEnv: ['GOOGLE_LOCATION_API_KEY', 'TINYMCE_EDITOR_API_KEY']

  # Build Backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/jobs-app-400516/jobs-portal/backend', './apps/backend']

  # Push images to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jobs-app-400516/jobs-portal/frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jobs-app-400516/jobs-portal/backend']

images:
  - 'gcr.io/jobs-app-400516/jobs-portal/frontend'
  - 'gcr.io/jobs-app-400516/jobs-portal/backend'

availableSecrets:
  secretManager:
  - versionName: projects/jobs-app-400516/secrets/google-location-api-key/versions/latest
    env: 'GOOGLE_LOCATION_API_KEY'
  - versionName: projects/jobs-app-400516/secrets/tinymce-editor-api-key/versions/latest
    env: 'TINYMCE_EDITOR_API_KEY'

options:
  logging: CLOUD_LOGGING_ONLY
