steps:
  # Budowanie obrazu dla Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/jobs-app-400516/jobs-portal/frontend', './apps/frontend', '--build-arg', 'VITE_GOOGLE_LOCATION_API_KEY=$_GOOGLE_LOCATION_API_KEY', '--build-arg', 'VITE_TINYMCE_EDITOR_API_KEY=$_TINYMCE_EDITOR_API_KEY']

  # Budowanie obrazu dla Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/jobs-app-400516/jobs-portal/backend', './apps/backend']

  # Pushowanie obrazów na Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jobs-app-400516/jobs-portal/frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jobs-app-400516/jobs-portal/backend']

images:
  - 'gcr.io/jobs-app-400516/jobs-portal/frontend'
  - 'gcr.io/jobs-app-400516/jobs-portal/backend'

substitutions:
  _GOOGLE_LOCATION_API_KEY: ''
  _TINYMCE_EDITOR_API_KEY: ''

options:
  logging: CLOUD_LOGGING_ONLY
