version: '3.3'
services:
  frontend:
    image: node:alpine
    container_name: frontend
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    env_file: .env
    working_dir: /app/frontend
    ports:
      - '${FRONTEND_PORT}:${FRONTEND_PORT}'
    networks:
      - bp-network
    tty: true
  backend:
    container_name: backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    networks:
      - bp-network
    ports:
      - '${BACKEND_PORT}:${BACKEND_PORT}'
    depends_on:
      - bp-pg-db
    links:
      - bp-pg-db
  bp-pg-db:
    image: postgres:alpine
    restart: always
    container_name: bp-pg-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bp-network
  pgadmin-portal:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin-portal
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_PASSWORD}'
      PGADMIN_DEFAULT_EMAIL: '${PGADMIN_USER}'
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - '${PGADMIN_PORT}:${PGADMIN_PORT}'
    depends_on:
      - bp-pg-db
    networks:
      - bp-network
volumes:
  pgdata:
  pgadmin:
networks:
  bp-network:
    driver: bridge
