FROM node:alpine
WORKDIR /app/backend
COPY . .
COPY package.json .
RUN chown -R node:node /app/backend/
RUN npm install --silent
RUN npm run build
USER node
RUN npm run migration:run

# Value set in .env file.
EXPOSE $BACKEND_PORT
CMD ["npm", "run", "prod"]